version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 60s
      retries: 120
    networks:
      - lms
    restart: unless-stopped

networks:
  lms:
    driver: bridge

volumes:
  postgres:
